### ISSUE TITLE
Account: Link / URL does not contain ":"

### ISSUE THREAD

**Issue by gruenheit** [pushpak1300/Secupass#131]
In the details and executed link the colon is missing, therefore the URL is wrong / wont work.

HTD:

- login
- create a new account
- edit link 
- fill in URL with leading protocol (http:// , https://)
- accomplish / fill in all needed data and save the account
- use latter …click link ( > go to website)
- link is broken (colon is missing)

**Comment by pushpak1300** [comment]
Can you fix the issue ?
If you can please make PR to repo.

**Comment by pushpak1300** [comment]
I tried to reproduce this bug and bug exist.
thanks for reporting.

**Comment by pushpak1300** [comment]
https://github.com/pushpak1300/Secupass/blob/fdbb7c2ed4f4d4210fce20b0251465c0ee8059ee/resources/views/accounts/accounts.blade.php#L40 
I am alredy adding http:// to saved links that's why colon is missing .You can check that [here](https://stackoverflow.com/questions/16694969/why-is-the-colon-missing-after-http-in-my-url).
If you can make PR that would be awesome!
